### ISSUE TITLE
Unable to unzip the downloaded database

### ISSUE THREAD

**Issue by Rohit-Satyam** [vrmarcelino/CCMetagen#38] opened 2022-05-29 11:32 UTC
Hi Developers!!

I am unable to extract the zipped file. It gives me the following error:
```
unzip ncbi_nt_kma.zip
Archive:  ncbi_nt_kma.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ncbi_nt_kma.zip or
        ncbi_nt_kma.zip.zip, and cannot find ncbi_nt_kma.zip.ZIP, period.

```

The commands I used were: 
```
nohup wget https://cloudstor.aarnet.edu.au/plus/s/vfKH9S8c5FVGBjV/download?path=%2F&files=ncbi_nt_kma.zip &
mv download?path=%2F ncbi_nt_kma.zip
```

**Comment by vrmarcelino** [comment] 2022-05-29 21:56
Hi!

It is possible that the download didn't complete or was corrupted.
Could you give it another try? It takes a while but generally doable without nohup.

Thanks!

**Comment by aberaslop** [comment] 2022-06-05 16:50
Hi! 
I am having the same problem as @Rohit-Satyam. I have tried to download it a couple of times, but I keep getting the same error. Any clue of what could be going wrong? Thanks!

**Comment by tarunpal33** [comment] 2022-06-08 13:42
Same problem while unzipping the nt database with below error:

bad CRC 94152301  (should be 4bdf57d7)
Any help about this?

**Comment by vrmarcelino** [comment] 2022-06-12 20:30
Hi!

I am sorry for taking so long to reply, I am on leave with little access to internet.
This is really weird, I couldn't reproduce this error when I tried a few weeks ago, but I will follow up on this as asap.

Thanks for your patience!

**Comment by vrmarcelino** [comment] 2022-06-22 08:24
Hi again,

My last two trials to download and unzip the database have also failed, though I got a different error. It seems that the files got corrupted during the server migration. I am following up on that and we will provide a solution asap.

**Comment by tarunpal33** [comment] 2022-06-22 08:54
Thanks, I made it last week after a number of attempts to download the
database.


Thanks & Regards
Dr. Tarun Pal
Postdoctoral Researcher
Zuckerberg Institute for Water Research
Blaustein Institutes for Desert Research
Ben-Gurion University of the Negev
Sede Boker Campus 84990, Israel

**Comment by vrmarcelino** [comment] 2022-07-18 05:34
Hi all,

This issue seems to be resolved. If not, please let me know.
Thanks a lot for your patience!

I'll close this for now but feel free to re-open it if you have problems.

**Comment by aberaslop** [comment] 2022-09-29 08:22
Hi, 
I still have the same problem. I would appreciate any help. Thank you!

L.

This is what I've done: 
> wget https://cloudstor.aarnet.edu.au/plus/s/vfKH9S8c5FVGBjV/download?path=%2F&files=ncbi_nt_kma.zip 
> mv download?path=%2F ncbi_nt_kma.zip
> unzip ncbi_nt_kma.zip

This is the error I am getting:

Archive:  ncbi_nt_kma.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ncbi_nt_kma.zip or
        ncbi_nt_kma.zip.zip, and cannot find ncbi_nt_kma.zip.ZIP, period.

**Comment by vrmarcelino** [comment] 2022-09-30 01:05
Hi,
Sorry for this and thanks for reporting. I have contacted the storage team again.
The problem seems to affect some of the mirror storage files, but not all, so trying to download it again might do the trick.
In any case, I will post any updates on this as soon as we get a solution.

**Comment by vrmarcelino** [comment] 2022-09-30 01:07
Could you also try:
wget "https://cloudstor.aarnet.edu.au/plus/s/vfKH9S8c5FVGBjV/download?path=%2F&files=ncbi_nt_kma.zip"

Thanks!

**Comment by aberaslop** [comment] 2022-09-30 13:45
Aha! Thank you so much, this worked! Very much appreciated :)

**Closed as completed** 2023-04-05 22:32 UTC
